name: Create tag and trigger deploy
on:
  push:
    branches:
      - main

jobs:
  bump:
    name: Create tag
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Create and push tag
        run: |
          git tag $(sed 's/chore(release): //g' <<< '${{ github.event.head_commit.message }}')
          git push origin --tags
  deploy-trigger:
    needs: bump
    name: Trigger deploy
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    uses: ./.github/workflows/ci-prod.yml
    secrets: inherit
